apiVersion: apps/v1
kind: Deployment
metadata:
  name: faq-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faq-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: faq-frontend
    spec:
      terminationGracePeriodSeconds: 60
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: faq-frontend
        image: oxfaq.azurecr.io/faq-frontend:5f1f8250be2ddfdffe4d3410262ca1b6f71f34e7
        envFrom:
            - secretRef:
                name: openai-secret
        ports:
        - containerPort: 3000
